version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    groups:
      routine-npm-updates:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Los_Angeles
    groups:
      routine-action-updates:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - dependencies
      - github-actions
